name = "Ledecka"
uuid = "9bc208b8-3aa8-11e8-19f7-8fdaaa57938d"
keywords = ["testing", "property based testing", "quickCheck", "memes", "arbitrary implementation"]
license = "BSD3"
desc = "Give your code a quickCheck before it gets off the chairlift. ğŸš¡â›·ï¸ "
authors = ["Polytomous! <polytomous@gmail.com>"]
version = "1.2.3"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
